#export SCT_REGION_NAME='us-east-1 eu-west-1 '
export SCT_REGION_NAME='["eu-west-1", "us-west-2", "us-east-1"]'
export SCT_CONFIG_FILES=test-cases/longevity/asias-multi-dc.yaml

# ami is generated by http://jenkins.scylladb.com/job/scylla-master/job/ami-test/56/parameters/
export SCT_AMI_ID_DB_SCYLLA='ami-09233216875aa2ecd ami-054ebfac2eced3edc ami-0253b5ee42c61e07e'
export SCT_FAILURE_POST_BEHAVIOR=keep
export SCT_INSTANCE_PROVISION=on_demand
export SCT_INTRA_NODE_COMM_PUBLIC=true
export SCT_IP_SSH_CONNECTIONS='public'

echo "start test ......."
#./docker/env/hydra.sh run-test longevity_test.LongevityTest.test_custom_time --backend aws --logdir /sct
./docker/env/hydra.sh run-test longevity_test.LongevityTest.test_foo --backend aws --logdir /sct
echo "end test ....."
